parser: '@typescript-eslint/parser'
parserOptions:
  extraFileExtensions: ['.json']
  project: './tsconfig.json'
  ecmaVersion: 2020
  sourceType: module
extends:
  - oclif
  - oclif-typescript
  - plugin:prettier/recommended
