parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2020
  sourceType: module
extends:
  - oclif
  - oclif-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
