#Place to configurate eslint settings

parser: babel-eslint
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - standard
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 'off'
