#Place to configurate eslint settings

parser: @typescript-eslint/parser
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures: 
    jsx: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
rules:
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 'off'
